name: SBOM Scan

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  sbom_scan:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies (Ubuntu)
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip python3-venv wget curl

          # create venv
          python3 -m venv sbom_env
          source sbom_env/bin/activate
          pip install --upgrade pip setuptools wheel virtualenv

      - name: Install PowerShell (Ubuntu)
        run: |
          wget https://github.com/PowerShell/PowerShell/releases/download/v7.5.0/powershell_7.5.0-1.deb_amd64.deb
          sudo dpkg -i powershell_7.5.0-1.deb_amd64.deb || true
          sudo apt-get --fix-broken install -y
          pwsh --version
          rm -rf powershell_7.5.0-1.deb_amd64.deb

      - name: Run python-install.sh
        run: |
          chmod +x ./python-install.sh
          ./python-install.sh

      - name: Run get-details.ps1
        shell: pwsh
        run: ./get-details.ps1

      - name: Run merge-details.ps1
        shell: pwsh
        run: ./merge-details.ps1

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: sbom-results
          path: |
            trivy-vulnerabilities.txt
            sbom-result.txt
          retention-days: 1
