name: SBOM Scan

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  sbom_scan:
    runs-on: self-hosted   # or "ubuntu-22.04" if you switch to GitHub-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies (macOS)
        run: |
          brew update
          brew install python3 pipx wget
          pipx install virtualenv
          python3 -m venv sbom_env
          source sbom_env/bin/activate
          pip install --upgrade pip setuptools wheel

      - name: Install PowerShell (macOS)
        run: |
          brew install --cask powershell
          pwsh --version

      - name: Run python-install.sh
        run: |
          chmod +x ./python-install.sh
          ./python-install.sh

      - name: Run get-details.ps1
        shell: pwsh
        run: ./get-details.ps1

      - name: Run merge-details.ps1
        shell: pwsh
        run: ./merge-details.ps1

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: sbom-results
          path: |
            trivy-vulnerabilities.txt
            sbom-result.txt
          retention-days: 1
